# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.7
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: latief.michael@gmail.com
author_name: LachTTT
contract_name: fullstackclaimcap
deployment_language: python
preset_name: starter
project_name: fullstackclaimcap

